import type { NextPage } from "next";
import Link from "next/link";
import React from "react";
import Layout from "./../components/Layout/Layout";
import useLanguage from "./../hooks/useLanguage";

const PrivacyPolicy: NextPage = () => {
    const lang = useLanguage();

    return (
        <Layout title="Privacy Policy" description="" lang={lang}>
            <section className="min-h-screen mx-0 md:mx-32 mt-32 mb-48 relative">
                <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
                <hr />

                <p className="my-4">
                    Typhe is committed to protecting your privacy. This Privacy Policy explains how your personal
                    information will be collected, used, and disclosed by Typhe. This privacy policy applies to our
                    website,{" "}
                    <Link href="/">
                        <a className="text-blue-500 underline">typhe.io</a>
                    </Link>
                    , and its associated subdomains (collectively, our &quot;Service&quot;). By registering an account,
                    you signify that you have read, understood, and agree to our collection, storage, use, and
                    disclosure of your personal information as described in this Privacy Policy.
                </p>

                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">Definition and Key terms</h2>
                <hr />
                <p className="mt-4 mb-2">For this privacy policy:</p>
                <ul className="list-inside list-disc">
                    <li>
                        <strong>Cookie - </strong> A small amount of data generated by a website and saved by your web
                        browser. It is used to identify your browser, provide analytics, remember information about you
                        such as your language preference or login information.
                    </li>
                    <li>
                        <strong>Country - </strong> where typhe or the owners of Typhe are based, in the Philippines.
                    </li>
                    <li>
                        <strong>Device - </strong> any internet connected device such as a phone, tablet, computer or
                        any other device that can be used to visit Typhe and use the services.
                    </li>
                    <li>
                        <strong>IP Address - </strong> Every device connected to the Internet is assigned a number known
                        as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks.
                        An IP address can often be used to identify the location from which a device is connecting to
                        the Internet.
                    </li>
                    <li>
                        <strong>Personal Data - </strong> any information that directly, indirectly, or in connection
                        with other information — including a personal identification number — allows for the
                        identification or identifiability of a natural person.
                    </li>
                    <li>
                        <strong>Testers or Users - </strong> refers to people who sign up in our website and take part
                        in the study.
                    </li>
                    <li>
                        <strong>Team - </strong> when this policy mentions Team,” “we,” “us,” or “our,” it refers to the
                        team at Typhe that is responsible for your information under this Privacy Policy.
                    </li>
                    <li>
                        <strong>Website - </strong> Typhe&apos;s site which can be accessed via this url:{" "}
                        <Link href="typhe.io">
                            <a className="text-blue-500 underline">typhe.io</a>
                        </Link>
                    </li>
                </ul>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">What information do we collect?</h2>
                <hr />
                <p className="mt-4 mb-2">
                    We collect information from you when you register and take part in the study. Information that we
                    collect includes:
                </p>
                <ul className="list-inside list-disc">
                    <li>Username/ Name</li>
                    <li>Phone Numbers</li>
                    <li>Address</li>
                    <li>Age</li>
                    <li>Typing-related data (gaze shifts, wpm, accuracy, consistency)</li>
                </ul>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">
                    How do we use the information that we collect?
                </h2>
                <hr />
                <p className="mt-4 mb-2">
                    Since the reason behind the creation of the typhe website is for data collection purpose for a
                    research being conducted on an Optimized Filipino Keyboard, data that is collected will be used to
                    analyze and create a better keyboard layout for the Filipino Language.
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">
                    Where and when is information collected from our users?
                </h2>
                <hr />
                <p className="mt-4 mb-2">
                    We will collect personal information that you submit to us. We will also collect information on the
                    actual testing date.
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">How Do We Use Your Email Address?</h2>
                <hr />
                <p className="mt-4 mb-2">
                    By submitting your email address on this website, you agree to receive emails from us. You can
                    cancel your participation in any of these email lists at any time by clicking on the opt-out link or
                    other unsubscribe option that is included in the respective email. We only send emails to people who
                    have authorized us to contact them, either directly, or through a third party. We do not send
                    unsolicited commercial emails, because we hate spam as much as you do. By submitting your email
                    address, you also agree to allow us to use your email address for customer audience targeting on
                    sites like Facebook, where we display custom advertising to specific people who have opted-in to
                    receive communications from us. Email addresses submitted only through the order processing page
                    will be used for the sole purpose of sending you information and updates pertaining to your order.
                    If, however, you have provided the same email to us through another method, we may use it for any of
                    the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from
                    receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">
                    Is the information collected through our service secure?
                </h2>
                <hr />
                <p className="mt-4 mb-2">
                    We take precautions to protect the security of your information. We have physical, electronic, and
                    managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and
                    correctly use your information. However, neither people nor security systems are foolproof,
                    including encryption systems. In addition, people can commit intentional crimes, make mistakes or
                    fail to follow policies. Therefore, while we use reasonable efforts to protect your personal
                    information, we cannot guarantee its absolute security. If applicable law imposes any
                    non-disclaimable duty to protect your personal information, you agree that intentional misconduct
                    will be the standards used to measure our compliance with that duty.
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">How Long Do We Keep Your Information?</h2>
                <hr />
                <p className="mt-4 mb-2">
                    We keep your information only so long as we need it for data analysis and fulfill the purposes
                    described in this policy. This is also the case for anyone that we share your information with and
                    who carries out services on our behalf. When we no longer need to use your information and there is
                    no need for us to keep it, we&apos;ll either remove it from our systems or depersonalize it so that
                    we can&apos;t identify you.
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">How Do We Protect Your Information?</h2>
                <hr />
                <p className="mt-4 mb-2">
                    We implement a variety of security measures to maintain the safety of your personal information when
                    submit or access your personal information. We offer the use of a secure server. We cannot, however,
                    ensure or warrant the absolute security of any information you transmit to us or guarantee that your
                    information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any
                    of our physical, technical, or managerial safeguards.
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">Governing Law</h2>
                <hr />
                <p className="mt-4 mb-2">
                    The laws of Philippines, excluding its conflicts of law rules, shall govern this Agreement and your
                    use of our service. Your use of our service may also be subject to other local, state, national, or
                    international laws. Specifically, we follow the{" "}
                    <Link href="https://www.privacy.gov.ph/data-privacy-act/">
                        <a className="text-blue-500 underline">Data Privacy Act of 2012</a>
                    </Link>
                    .
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">Your Consent</h2>
                <hr />
                <p className="mt-4 mb-2">By registering an account you consent to this Privacy Policy.</p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">Cookies</h2>
                <hr />
                <p className="mt-4 mb-2">
                    We use &quot;Cookies&quot; to identify the areas of our website that you have visited. A Cookie is a
                    small piece of data stored on your computer or mobile device by your web browser. We use Cookies to
                    authenticate our users that have registered. Most web browsers can be set to disable the use of
                    Cookies. However, if you disable Cookies, you may not be able to access functionality on our website
                    correctly or at all.
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">Changes To Our Privacy Policy</h2>
                <hr />
                <p className="mt-4 mb-2">
                    If we decide to change our privacy policy, we will post those changes on this page, and/or update
                    the Privacy Policy modification date below.
                </p>
                <h2 className="text:xl md:text-3xl font-semibold mt-8 mb-4">Tracking Technologies</h2>
                <hr />
                <ul className="list-inside list-disc mt-4">
                    <li>
                        Cookies
                        <br />
                        We use Cookies to enhance the performance and functionality of our service but are non-essential
                        to their use. However, without these cookies, certain functionality like videos may become
                        unavailable or you would be required to enter your login details every time you visit our
                        service as we would not be able to remember that you had logged in previously.
                    </li>

                    <li>
                        Local Storage
                        <br />
                        Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for
                        storing client-side data. Web storage supports persistent data storage, similar to cookies but
                        with a greatly enhanced capacity and no information stored in the HTTP request header.
                    </li>
                    <li>
                        Session Storage
                        <br />
                        We use &quot;Sessions&quot; to identify the areas of our website that you have visited. A
                        Session is a small piece of data stored on your computer or mobile device by your web browser.
                    </li>
                </ul>
            </section>
        </Layout>
    );
};

export default PrivacyPolicy;
