import type { NextPage } from "next";
import Link from "next/link";
import React from "react";
import Layout from "./../components/Layout/Layout";
import useLanguage from "./../hooks/useLanguage";

const PrivacyPolicy: NextPage = () => {
    const lang = useLanguage();

    return (
        <Layout title="Privacy Policy" description="" lang={lang}>
            <div className="flex items-center justify-center my-48">
                <section className="w-3/4 max-w-5xl font-default">
                    <h1 className="font-extrabold text-3xl sm:text-4xl sm:leading-snug md:text-5xl md:leading-snug mb-8">
                        Privacy Policy
                    </h1>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        Typhe is committed to protecting your privacy. This
                        Privacy Policy explains how your personal information
                        will be collected, used, and disclosed by Typhe. This
                        privacy policy applies to our website,{" "}
                        <Link href="/">
                            <a className="text-blue-500 underline">typhe.io</a>
                        </Link>
                        , and its associated subdomains (collectively, our
                        &quot;Service&quot;). By registering an account, you
                        signify that you have read, understood, and agree to our
                        collection, storage, use, and disclosure of your
                        personal information as described in this Privacy
                        Policy.
                    </p>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        In compliance with the Data Privacy Act of 2012
                        (RA10173) and its Implementing Rules and Regulations
                        (IPR) effective since September 9, 2016, I am
                        authorizing these student researchers to:
                        <ul className="list-outside list-disc mt-4 mx-8 space-y-4 font-regular text-md md:text-lg lg:text-lg">
                            <li>
                                Use my personal data, which includes my name,
                                and age range, gathered for their undergraduate
                                thesis.{" "}
                            </li>

                            <li>
                                Store my personal data for the analysis of
                                results and the accomplishment of their
                                undergraduate thesis.
                            </li>
                        </ul>
                    </p>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        By submitting, you are agreeing with the terms above.
                        Rest assured your data will be used only for the reasons
                        listed above and only by the entities stated in this
                        terms.
                    </p>

                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        Definition and Key terms
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">For this privacy policy:</p>
                    <ul className="list-outside list-disc mt-4 mx-8 space-y-4 font-regular text-md md:text-lg lg:text-lg">
                        <li>
                            <strong>Cookie</strong>
                            <br />A small amount of data generated by a website
                            and saved by your web browser. It is used to
                            identify your browser, provide analytics, remember
                            information about you such as your language
                            preference or login information.
                        </li>
                        <li>
                            <strong>Country</strong>
                            <br />
                            Where Typhe or the owners of Typhe are based, in the
                            Philippines.
                        </li>
                        <li>
                            <strong>Device</strong>
                            <br />
                            Any internet connected device such as a phone,
                            tablet, computer or any other device that can be
                            used to visit Typhe and use the services.
                        </li>
                        <li>
                            <strong>IP Address</strong>
                            <br />
                            Every device connected to the Internet is assigned a
                            number known as an Internet protocol (IP) address.
                            These numbers are usually assigned in geographic
                            blocks. An IP address can often be used to identify
                            the location from which a device is connecting to
                            the Internet.
                        </li>
                        <li>
                            <strong>Personal Data</strong>
                            <br />
                            Any information that directly, indirectly, or in
                            connection with other information — including a
                            personal identification number — allows for the
                            identification or identifiability of a natural
                            person.
                        </li>
                        <li>
                            <strong>Testers or Users</strong>
                            <br />
                            Refers to people who sign up in our website and take
                            part in the study.
                        </li>
                        <li>
                            <strong>Team</strong>
                            <br />
                            When this policy mentions Team,” “we,” “us,” or
                            “our,” it refers to the team at Typhe that is
                            responsible for your information under this Privacy
                            Policy.
                        </li>
                        <li>
                            <strong>Website</strong>
                            <br />
                            Typhe&apos;s site which can be accessed via this
                            url:{" "}
                            <Link href="typhe.io">
                                <a className="text-blue-500 underline">
                                    typhe.io
                                </a>
                            </Link>
                        </li>
                    </ul>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        What information do we collect?
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        We collect information from you when you register and
                        take part in the study. Information that we collect
                        includes:
                    </p>
                    <ul className="list-outside list-disc mt-4 mx-8 space-y-4 font-regular text-md md:text-lg lg:text-lg">
                        <li>
                            <strong>Username/ Name</strong>
                        </li>
                        <li>
                            <strong>Phone Numbers</strong>
                        </li>
                        <li>
                            <strong>Address</strong>
                        </li>
                        <li>
                            <strong>Age</strong>
                        </li>
                        <li>
                            <strong>Gaze Shifts</strong>
                            <br />
                            Number of times a user looks from monitor to
                            keyboard.
                        </li>
                        <li>
                            <strong>Words Per Minute</strong>
                            <br />
                            The user&apos;s average number of correct words they
                            can type in a minute.
                        </li>
                        <li>
                            <strong>Typing Accuracy</strong>
                            <br />
                            The user&apos;s percentage of correctly pressed
                            keys.
                        </li>
                        <li>
                            <strong>Typing Consistency</strong>
                            <br />
                            Variance of a user&apos;s words per minute.
                        </li>
                    </ul>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        How do we use the information that we collect?
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        Since the reason behind the creation of the Typhe
                        website is for data collection purpose for a research
                        being conducted on an Optimized Filipino Keyboard, data
                        that is collected will be used to analyze and create a
                        better keyboard layout for the Filipino Language.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        Where and when is information collected from our users?
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        We will collect personal information that you submit to
                        us. We will also collect information on the actual
                        testing date.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        How do we use your email address?
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        By submitting your email address on this website, you
                        agree to receive emails from us. You can cancel your
                        participation in any of these email lists at any time by
                        clicking on the opt-out link or other unsubscribe option
                        that is included in the respective email. We only send
                        emails to people who have authorized us to contact them,
                        either directly, or through a third party. We do not
                        send unsolicited commercial emails, because we hate spam
                        as much as you do. By submitting your email address, you
                        also agree to allow us to use your email address for
                        customer audience targeting on sites like Facebook,
                        where we display custom advertising to specific people
                        who have opted-in to receive communications from us.
                        Email addresses submitted only through the order
                        processing page will be used for the sole purpose of
                        sending you information and updates pertaining to your
                        order. If, however, you have provided the same email to
                        us through another method, we may use it for any of the
                        purposes stated in this Policy. Note: If at any time you
                        would like to unsubscribe from receiving future emails,
                        we include detailed unsubscribe instructions at the
                        bottom of each email.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        Is the information collected through our service secure?
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        We take precautions to protect the security of your
                        information. We have physical, electronic, and
                        managerial procedures to help safeguard, prevent
                        unauthorized access, maintain data security, and
                        correctly use your information. However, neither people
                        nor security systems are foolproof, including encryption
                        systems. In addition, people can commit intentional
                        crimes, make mistakes or fail to follow policies.
                        Therefore, while we use reasonable efforts to protect
                        your personal information, we cannot guarantee its
                        absolute security. If applicable law imposes any
                        non-disclaimable duty to protect your personal
                        information, you agree that intentional misconduct will
                        be the standards used to measure our compliance with
                        that duty.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        How long do we keep your information?
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        We keep your information only so long as we need it for
                        data analysis and fulfill the purposes described in this
                        policy. This is also the case for anyone that we share
                        your information with and who carries out services on
                        our behalf. When we no longer need to use your
                        information and there is no need for us to keep it,
                        we&apos;ll either remove it from our systems or
                        depersonalize it so that we can&apos;t identify you.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        How do we protect your information?
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        We implement a variety of security measures to maintain
                        the safety of your personal information when submit or
                        access your personal information. We offer the use of a
                        secure server. We cannot, however, ensure or warrant the
                        absolute security of any information you transmit to us
                        or guarantee that your information on the Service may
                        not be accessed, disclosed, altered, or destroyed by a
                        breach of any of our physical, technical, or managerial
                        safeguards.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        Governing Law
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        The laws of Philippines, excluding its conflicts of law
                        rules, shall govern this Agreement and your use of our
                        service. Your use of our service may also be subject to
                        other local, state, national, or international laws.
                        Specifically, we follow the{" "}
                        <Link href="https://www.privacy.gov.ph/data-privacy-act/">
                            <a className="text-blue-500 underline">
                                Data Privacy Act of 2012
                            </a>
                        </Link>
                        .
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        Your consent
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        By registering an account you consent to this Privacy
                        Policy.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        Cookies
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        We use &quot;Cookies&quot; to identify the areas of our
                        website that you have visited. A Cookie is a small piece
                        of data stored on your computer or mobile device by your
                        web browser. We use Cookies to authenticate our users
                        that have registered. Most web browsers can be set to
                        disable the use of Cookies. However, if you disable
                        Cookies, you may not be able to access functionality on
                        our website correctly or at all.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        Changes to our Privacy Policy
                    </h2>

                    <p className="my-4 font-regular text-md md:text-lg lg:text-lg">
                        If we decide to change our privacy policy, we will post
                        those changes on this page, and/or update the Privacy
                        Policy modification date below.
                    </p>
                    <h2 className="text-2xl font-bold mt-16 mb-8">
                        Tracking Technologies
                    </h2>

                    <ul className="list-outside list-disc mt-4 mx-8 space-y-4 font-regular text-md md:text-lg lg:text-lg">
                        <li>
                            <strong>Cookies</strong>
                            <br />
                            We use Cookies to enhance the performance and
                            functionality of our service but are non-essential
                            to their use. However, without these cookies,
                            certain functionality like videos may become
                            unavailable or you would be required to enter your
                            login details every time you visit our service as we
                            would not be able to remember that you had logged in
                            previously.
                        </li>

                        <li>
                            <strong>Local Storage</strong>
                            <br />
                            Local Storage sometimes known as DOM storage,
                            provides web apps with methods and protocols for
                            storing client-side data. Web storage supports
                            persistent data storage, similar to cookies but with
                            a greatly enhanced capacity and no information
                            stored in the HTTP request header.
                        </li>
                        <li>
                            <strong>Session Storage</strong>
                            <br />
                            We use &quot;Sessions&quot; to identify the areas of
                            our website that you have visited. A Session is a
                            small piece of data stored on your computer or
                            mobile device by your web browser.
                        </li>
                    </ul>
                </section>
            </div>
        </Layout>
    );
};

export default PrivacyPolicy;
